# Generated by Django 4.0 on 2022-01-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Vin'),
        ),
    ]
