# Generated by Django 3.2.9 on 2021-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20211121_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='message_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
