# Generated by Django 4.0 on 2022-02-13 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 20, 9, 43, 86923)),
        ),
    ]
