# Generated by Django 4.0 on 2022-02-13 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_alter_article_username_alter_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 20, 12, 7, 383628)),
        ),
    ]
