# Generated by Django 4.0 on 2022-02-10 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_alter_article_username_alter_favourite_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_save',
            field=models.DateField(default=datetime.date(2022, 2, 11)),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.article')),
            ],
        ),
    ]
