# Generated by Django 4.0 on 2022-02-14 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_rename_username_article_user_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_save',
            field=models.DateField(default=datetime.date(2022, 2, 14)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 32, 32, 538916)),
        ),
    ]
