# Generated by Django 4.0 on 2022-02-11 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appmain', '0003_alter_article_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 11, 19, 31, 52, 700208))),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Like',
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
