# Generated by Django 4.0 on 2022-02-11 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_alter_comment_date_alter_like_id_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='id_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 21, 48, 29, 667)),
        ),
    ]
