# Generated by Django 4.0 on 2022-02-18 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0008_alter_article_image_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_save',
            field=models.DateField(default=datetime.date(2022, 2, 18)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 19, 9, 26, 900186)),
        ),
    ]
