# Generated by Django 4.0 on 2022-02-18 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0011_alter_article_date_of_save_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 0, 52, 44, 264540)),
        ),
    ]
