# Generated by Django 3.2 on 2022-02-21 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0013_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_save',
            field=models.DateField(default=datetime.date(2022, 2, 21)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 9, 29, 19, 637629)),
        ),
    ]
