# Generated by Django 3.2 on 2022-02-22 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0014_auto_20220221_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_of_save',
            field=models.DateField(default=datetime.date(2022, 2, 22)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 21, 25, 0, 960364)),
        ),
    ]
