# Generated by Django 5.0.3 on 2024-03-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
