# Generated by Django 4.0.1 on 2022-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.CharField(max_length=512, verbose_name='Text')),
                ('id_of_movie', models.CharField(max_length=128, unique=True, verbose_name='Id of movie')),
                ('user', models.CharField(max_length=255, verbose_name='User login')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
